Alert modal
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend pull request #19
Opened 2021-09-19 02:40 UTC by emysdias

## Issue 
#15 

## Descrição
Foi adicionado o modal dos alertas da aplicação.

## Screenshots (Se houver necessidade):
![image](https://user-images.githubusercontent.com/52640974/133913418-6a6a17e2-aaba-4a01-861a-f5cdcb08b9ce.png)

## Checklist:
- [x] Feito modal
- [x] Feito testes
- [x] Falta só o botão q será feito em outra branch

## Como validar?
Rodando a aplicação

2021-09-19 21:20 UTC, lboaventura25 commented
Ficou massa!
O único ponto é por que a propriedade icon do alertModal é uma string?

2021-09-19 22:35 UTC, sergiosacj commented on frontend/src/__tests__/components/Modal/AlertModal/AlertModal.test.tsx
> +import AlertModal from 'components/Modal/AlertModal';
Esse daqui é o padrão que usamos.

2021-09-19 22:35 UTC, sergiosacj commented on frontend/src/components/Modal/AlertModal/index.tsx
> +import Icons from '../../../utils/assets';
Esses daqui não.

2021-09-19 22:35 UTC, sergiosacj commented on frontend/src/utils/assets.ts
> +import simboloOk from '../assets/simbolo_ok.svg';
Mesma coisa aqui.

2021-09-19 22:35 UTC, sergiosacj requested changes
Emily, os códigos que entraram seguem o padrão de imports pelo path completo. Se puder manter esse padrão.

2021-09-19 23:51 UTC, emysdias commented
> Ficou massa!
> O único ponto é por que a propriedade icon do alertModal é uma string?

Pq passa o nome de uma string pra ele

2021-09-19 23:55 UTC, lboaventura25 commented
> > Ficou massa!
> > O único ponto é por que a propriedade icon do alertModal é uma string?
> 
> Pq passa o nome de uma string pra ele

Podia utilizar o icon nesse caso, ele só está sendo utilizado como um "booleano" por enquanto

2021-09-20 00:04 UTC, emysdias commented
> > > Ficou massa!
> > > O único ponto é por que a propriedade icon do alertModal é uma string?
> > 
> > 
> > Pq passa o nome de uma string pra ele
> 
> Podia utilizar o icon nesse caso, ele só está sendo utilizado como um "booleano" por enquanto

é q tem q determinar qual ícone vai aparecer, e deixar só "icon" não faz muito sentido sem definir qual icone

2021-09-20 00:11 UTC, sergiosacj approved these changes
Valeu @emysdias, por mim já está tudo ok.

2021-09-20 00:17 UTC, merged