Adiciona tela de Menu
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend pull request #32
Opened 2021-09-28 21:55 UTC by lboaventura25

## Issue 
Resolves #17 
Resolver #26 

## Descrição
Adiciona tela de Menu com responsividade e integração com a api.

## Screenshots (Se houver necessidade):

![Captura de tela de 2021-09-28 18-52-48](https://user-images.githubusercontent.com/49161615/135170906-9bfeac86-beeb-4419-978e-3486a8cff86c.png)
![Captura de tela de 2021-09-28 18-52-52](https://user-images.githubusercontent.com/49161615/135170909-adf1d5fb-910b-4694-a74c-da54d808c31f.png)
![Captura de tela de 2021-09-28 18-52-28](https://user-images.githubusercontent.com/49161615/135170891-c295082f-927d-4387-a44c-b8d450a65a48.png)
![Captura de tela de 2021-09-28 18-52-31](https://user-images.githubusercontent.com/49161615/135170895-5f354050-562e-40f6-83f5-dd9177b3293c.png)
![Captura de tela de 2021-09-28 18-52-41](https://user-images.githubusercontent.com/49161615/135170901-cec074c2-7d92-4428-be38-6bd3a89535ae.png)

## Checklist:

- [ ] Meu código segue os padrões de estilo desse projeto.
- [ ] Minhas alterações necessitam de atualização na documentação.
- [ ] Eu atualizei a documentação de acordo com as mudanças feitas nesse PR.

## Como validar?
Passear pela aplicação e checar se está tudo certo no fluxo da tela de Menu.

2021-10-01 03:01 UTC, emysdias requested changes
![image](https://user-images.githubusercontent.com/52640974/135558693-2baaa6c6-05a8-47e7-95ff-77793a7cdb9e.png)
Ta dando erro no terminal
![image](https://user-images.githubusercontent.com/52640974/135558723-6b74d61a-a458-4426-ba59-9454449f9c73.png)
na minha tela o último botão fica cortado. E em relação a responsividade eu não sou muito fã de ter 2 scrolls na mesma tela, como sua tela é maior q a minha não mostrou mas na minha ficou, se for algo q não vai ocupar muito tempo é show, mas se ocupar eu aceito assim mesmo depois de arrumar a questão do botão e do warning

2021-10-01 11:18 UTC, sergiosacj commented
> heavy_check_mark Deploy Preview for _tanamesa_ ready!
> 
> hammer Explore the source changes: [2e78ef9](https://github.com/UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend/commit/2e78ef9c469b11e6bbfcbbc3f353d58a023df4a2)
> 
> mag Inspect the deploy log: [https://app.netlify.com/sites/tanamesa/deploys/6156edc3cea831f017a5c09c](https://app.netlify.com/sites/tanamesa/deploys/6156edc3cea831f017a5c09c?utm_source=github&utm_campaign=bot_dl)
> 
> sunglasses Browse the preview: [https://deploy-preview-32--tanamesa.netlify.app/](https://deploy-preview-32--tanamesa.netlify.app/?utm_source=github&utm_campaign=bot_dp)

O link de preview voltou a funcionar, arrumei os problemas do deploy e da CI do gitlab

2021-10-01 14:07 UTC, alvesitalo requested changes
O menu lateral não rola até o final mesmo com a barra de rolagem:

![Captura de Tela 2021-10-01 às 11 05 31](https://user-images.githubusercontent.com/35741521/135633583-bc415e49-8b15-4a84-8553-f7b24ca5b8ef.png)

Os outros detalhes já foram falados 😄

2021-10-02 22:51 UTC, emysdias requested changes
![image](https://user-images.githubusercontent.com/52640974/135733656-6139083f-fb4a-4840-865c-8b6ab5f985cd.png)
ainda continua o problema do botão e do scroll

2021-10-02 22:51 UTC, emysdias commented
o scroll vou ser tão criteriosa não kkkkkkkkkkkkk mas o ruim q o botão não aparece

2021-10-03 12:55 UTC, lboaventura25 commented
@emysdias , ve se resolve kkkkkkk
Eu não tenho esse problema do botão cortar, aí tá meio dificil de corrigir, se puder corrigir pra mim kkkkk

2021-10-03 13:06 UTC, sergiosacj commented
@lboaventura25 @emysdias só dando meus 2 centavos, testei esse fluxo no browse preview e nenhum dos problemas permaneceram. Se puderem verificar utilizando o link do browse preview do netlify também.

Acredito que tudo foi corrigido e podemos fazer o merge, mas vou deixar a @emysdias tomar a decisão final.

2021-10-04 00:09 UTC, emysdias approved these changes
Eu vou aceitar, mas ainda continua. Depois a gente faz uma issue pra arrumar

2021-10-04 00:09 UTC, merged