Cria gerenciador de estado do tema
UnBArqDsw2021-1/2021.1_G02_TaNaMesa_Frontend pull request #7
Opened 2021-09-08 01:25 UTC by lboaventura25

## Issue 
Resolves #4

## Descrição
Cria gerenciador de estado do tema da aplicação.

## Screenshots (Se houver necessidade):

- Tema padrão:
![Captura de tela de 2021-09-07 22-22-38](https://user-images.githubusercontent.com/49161615/132430676-8d5738f7-cefe-405e-834b-65166411893a.png)

- Tema escuro:
![Captura de tela de 2021-09-07 22-22-35](https://user-images.githubusercontent.com/49161615/132430702-bd448163-92c4-4e9c-8897-ff9bad911176.png)

## Checklist:

- [x] Meu código segue os padrões de estilo desse projeto.
- [ ] Minhas alterações necessitam de atualização na documentação.
- [ ] Eu atualizei a documentação de acordo com as mudanças feitas nesse PR.

## Como validar?
Rodar a aplicação e clicar no botão de troca de tema e vẽ se tudo ocorre corretamente. Abrir o localStorage e checar se está criadno o '@TaNaMesa:theme' com o valor 'default' ou 'dark'.

2021-09-08 01:34 UTC, lboaventura25 commented
Deploy da branch https://deploy-preview-7--tanamesa.netlify.app/

2021-09-10 11:45 UTC, emysdias requested changes
![image](https://user-images.githubusercontent.com/52640974/132847997-1f6d7567-0e0f-4268-a43c-808dd3ee9c28.png)
Esses 3 parecem diferentes da paleta do figma. O q eu vi la são esses:
primary02: '#7F2726',
  primary03: '#B96738',
  primary04: '#A35E4E',

![image](https://user-images.githubusercontent.com/52640974/132848262-047324cd-686c-4065-adbd-1e19f521709f.png)
acho q esse cinza devia estar tbm: C4C4C4

![image](https://user-images.githubusercontent.com/52640974/132848398-3f535749-6e68-4382-ad50-6f7797ae07ec.png)
tem esse vermelho tbm q na paleta ta secondaryRed: '#D62631', mas vi aqui q é EB4040, a não ser q seja outro vermelho

Acho q são esses q vi por enquanto

2021-09-10 12:20 UTC, lboaventura25 commented
@emysdias , as cores foram coletadas da identidade visual. No entanto, concordo com voce que deveria ter olhado o figma kkkkkk.
Vou colocar as cores que faltaram lá agora! :smiley:

2021-09-10 12:39 UTC, emysdias commented
> @emysdias , as cores foram coletadas da identidade visual. No entanto, concordo com voce que deveria ter olhado o figma kkkkkk.
> Vou colocar as cores que faltaram lá agora!

as primarys vai deixar as q já estão no theme?

2021-09-10 12:46 UTC, emysdias approved these changes
showww 🏆

2021-09-10 13:37 UTC, tsrrodrigues approved these changes
Os caras são bons mesmo!!

2021-09-10 13:37 UTC, merged